-- MySQL Script generated by MySQL Workbench
-- 12/01/22 12:29:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Tecni_uasd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tecni_uasd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tecni_uasd` DEFAULT CHARACTER SET utf8 ;
USE `Tecni_uasd` ;

-- -----------------------------------------------------
-- Table `Tecni_uasd`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tecni_uasd`.`Clientes` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tecni_uasd`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tecni_uasd`.`Vendedor` (
  `id_vendedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(11) NULL,
  PRIMARY KEY (`id_vendedor`),
  UNIQUE INDEX `id_vendedor_UNIQUE` (`id_vendedor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tecni_uasd`.`Garantia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tecni_uasd`.`Garantia` (
  `id_garantia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `meses_garantia` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_garantia`),
  UNIQUE INDEX `id_garantia_UNIQUE` (`id_garantia` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tecni_uasd`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tecni_uasd`.`Proveedor` (
  `id_proveedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `id_proveedor_UNIQUE` (`id_proveedor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tecni_uasd`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tecni_uasd`.`Marca` (
  `id_marca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`),
  UNIQUE INDEX `id_marca_UNIQUE` (`id_marca` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tecni_uasd`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tecni_uasd`.`Equipo` (
  `id_equipo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `id_marca` INT UNSIGNED NOT NULL,
  `id_proveedor` INT UNSIGNED NOT NULL,
  `id_garantia` INT UNSIGNED NOT NULL,
  `informacion_tecnica` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id_equipo`),
  UNIQUE INDEX `id_equipo_UNIQUE` (`id_equipo` ASC),
  INDEX `fk_garantia_idx` (`id_garantia` ASC),
  INDEX `fk_proveedor_idx` (`id_proveedor` ASC),
  INDEX `fk_marca_idx` (`id_marca` ASC),
  CONSTRAINT `fk_garantia`
    FOREIGN KEY (`id_garantia`)
    REFERENCES `Tecni_uasd`.`Garantia` (`id_garantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Tecni_uasd`.`Proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `Tecni_uasd`.`Marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tecni_uasd`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Tecni_uasd`.`Factura` (
  `id_factura` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `id_vendedor` INT UNSIGNED NOT NULL,
  `tipoVenta` VARCHAR(15) NOT NULL,
  `id_equipo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_factura`),
  UNIQUE INDEX `id_factura_UNIQUE` (`id_factura` ASC),
  INDEX `fk_cliente_idx` (`id_cliente` ASC),
  INDEX `fk_vendedor_idx` (`id_vendedor` ASC),
  INDEX `fk_equipo_idx` (`id_equipo` ASC),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Tecni_uasd`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `Tecni_uasd`.`Vendedor` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `Tecni_uasd`.`Equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ----------------
-- set 'clientes' 
-- ----------------
insert into clientes(nombre,apellido,cedula) values("Juana","Mendez","40200000001");
insert into clientes(nombre,apellido,cedula) values("Pedro","Carvajal","40200000002");
insert into clientes(nombre,apellido,cedula) values("Daniela","Jimenez","40200000003");

-- ----------------
-- set garantias --
-- ----------------

insert into garantia(meses_garantia) values(12);
insert into garantia(meses_garantia) values(24);

-- ----------------
--  set marca   --
-- ----------------

insert into marca(nombre) values("Toyota");
insert into marca(nombre) values("Fun-chan-gan");
insert into marca(nombre) values("Hyundai");

-- ----------------
--  set proveedor   --
-- ----------------

insert into proveedor(nombre) values("Distribuidora Corripio");

-- ----------------
--  set vendedor   --
-- ----------------

insert into vendedor(nombre,apellido,cedula) values("Julio","Alcantara","40100000001");
insert into vendedor(nombre,apellido,cedula) values("Manuela","Lopez","40100000002");


USE `Tecni_uasd`;

DELIMITER $$
USE `Tecni_uasd`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Tecni_uasd`.`Factura_BEFORE_INSERT` BEFORE INSERT ON `Factura` FOR EACH ROW
BEGIN
	if new.id_factura>1000
		then
			set new.id_factura=null;
	end if;
END$$


delimiter $$

CREATE PROCEDURE `descripcion_de_los_equipos`(nombre varchar(45),marca varchar(45))
BEGIN
	SELECT 
		nombre,
        precio,
        marca.nombre as marca,
        proveedor.nombre as proveedor,garantia.meses_garantia as garantia 
        from equipo,proveedor,marca,garantia 
        where equipo.nombre=nombre and marca.nombre=marca and proveedor.id_proveedor=equipo.id_proveedor and marca.id_marca=equipo.id_marca and garantia.id_garantia=equipo.id_garantia;
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `estatus_cuentas_por_cobrar_a_credito`()
BEGIN
	select concat(concat(clientes.nombre," "),clientes.apellido) as cliente,
		equipo.precio as monto,
        fecha,
        vendedor.nombre as vendedor,
        equipo.nombre as equipo
		from factura,clientes,vendedor,equipo
		where factura.tipoVenta="credito" and clientes.id_cliente=factura.id_cliente and vendedor.id_vendedor=factura.id_vendedor and equipo.id_equipo=factura.id_equipo;
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `existencia_de_garantia`(nombre varchar(45),marca varchar(45))
BEGIN
	select equipo.nombre as equipo,
		marca.nombre as marca,
        garantia.meses_garantia as garantia
		from equipo,garantia,marca
        where equipo.nombre=nombre and marca.nombre=marca and equipo.id_marca=marca.id_marca and equipo.id_garantia=garantia.id_garantia;
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `garantia_por_cliente`(cedula varchar(15))
BEGIN
	select concat(concat(clientes.nombre," "),clientes.apellido) as cliente,equipo.nombre as equipo,equipo.marca as marca,equipo.meses_garantia as garantia 
		from clientes,factura,(select equipo.id_equipo,equipo.nombre,marca.nombre as marca,garantia.meses_garantia 
									from equipo,garantia,marca 
									where equipo.id_garantia=garantia.id_garantia and equipo.id_marca=marca.id_marca) as equipo
		where clientes.cedula=cedula and clientes.id_cliente=factura.id_cliente and factura.id_equipo=equipo.id_equipo;
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `informacion_tecnica_del_producto`(nombre varchar(45),marca varchar(15))
BEGIN
	select marca.nombre as marca,equipo.nombre as equipo,informacion_tecnica 
		from equipo,marca
        where equipo.id_marca=marca.id_marca;
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `informe_equipos_vendidos_por_vendedor`(mes int,cedula varchar(15))
BEGIN
	select concat(concat(vendedor.nombre," "),vendedor.apellido) as vendedor,factura.fecha as fecha, concat(concat(marca.nombre," "),equipo.nombre) as equipo,equipo.precio
    from factura,vendedor,equipo,marca
    where vendedor.cedula=cedula and vendedor.id_vendedor=factura.id_vendedor and equipo.id_equipo=factura.id_equipo and marca.id_marca=equipo.id_marca and Month(factura.fecha)=mes;
    
END $$

delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `informe_facturas_mensuales`(mes int)
BEGIN
	select 
		factura.id_factura,
        factura.fecha,
        concat(concat(clientes.nombre," "),clientes.apellido) as cliente,
        equipo,
        precio,
        marca,
        garantia
	from 
		factura,
        clientes,
        (select 
		equipo.id_equipo,
		equipo.nombre as equipo,
		equipo.precio,
		marca.nombre as marca,
        garantia.meses_garantia as garantia
		from 
			equipo,
			marca,
			garantia
		where 
			equipo.id_garantia=garantia.id_garantia 
			and equipo.id_marca=marca.id_marca) as equipo
	where
		factura.id_cliente=clientes.id_cliente
        and equipo.id_equipo=factura.id_equipo
        and month(factura.fecha)=mes;
	
END $$

delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `informe_ventas_a_credito`(mes int)
BEGIN
	select 
		factura.id_factura,
        factura.fecha,
        concat(concat(clientes.nombre," "),clientes.apellido) as cliente,
        equipo,
        precio,
        marca,
        garantia
	from 
		factura,
        clientes,
        (select 
		equipo.id_equipo,
		equipo.nombre as equipo,
		equipo.precio,
		marca.nombre as marca,
        garantia.meses_garantia as garantia
		from 
			equipo,
			marca,
			garantia
		where 
			equipo.id_garantia=garantia.id_garantia 
			and equipo.id_marca=marca.id_marca) as equipo
	where
		factura.id_cliente=clientes.id_cliente
        and equipo.id_equipo=factura.id_equipo
        and factura.tipoVenta="credito"
        and month(factura.fecha)=mes;
	
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `informe_ventas_al_contado`(mes int)
BEGIN
	select 
		factura.id_factura,
        factura.fecha,
        concat(concat(clientes.nombre," "),clientes.apellido) as cliente,
        equipo,
        precio,
        marca,
        garantia
	from 
		factura,
        clientes,
        (select 
		equipo.id_equipo,
		equipo.nombre as equipo,
		equipo.precio,
		marca.nombre as marca,
        garantia.meses_garantia as garantia
		from 
			equipo,
			marca,
			garantia
		where 
			equipo.id_garantia=garantia.id_garantia 
			and equipo.id_marca=marca.id_marca) as equipo
	where
		factura.id_cliente=clientes.id_cliente
        and equipo.id_equipo=factura.id_equipo
        and factura.tipoVenta="contado"
        and month(factura.fecha)=mes;
	
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `set_cliente`(nombre varchar(45),apellido varchar(45),cedula varchar(15))
BEGIN
	insert into clientes(nombre,apellido,cedula) values(nombre,apellido,cedula);
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `set_equipo`(nombre varchar(45),precio double,proveedor varchar(45),marca varchar(45),garantia varchar(45),informacionTecnica varchar(1024))
BEGIN
	set @idMarca=(select 
			id_marca
			from marca 
			where marca.nombre=marca);
	set @idProveedor=(select 
			id_proveedor
            from proveedor
            where proveedor.nombre=proveedor);
	set @idGarantia=(select 
			id_garantia
            from garantia
            where garantia.meses_garantia=garantia);
    
	insert equipo(nombre,precio,id_marca,id_proveedor,id_garantia,informacion_tecnica) 
		values(
			nombre,
            precio,
			@idMarca,
            @idProveedor,
            @idGarantia,
            informacionTecnica);
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `set_factura`(cedula varchar(45),vendedor varchar(45),equipo varchar(45),tipoVenta varchar(15))
BEGIN
		
    set @idCliente=(select 
			id_cliente
			from clientes 
			where clientes.cedula=cedula);
	set @idVendedor=(select 
			id_vendedor
            from vendedor
            where concat(concat(vendedor.nombre," "),vendedor.apellido)=vendedor);
	set @idEquipo=(select 
			id_equipo
            from equipo,marca
            where concat(concat(marca.nombre," "),equipo.nombre)=equipo);
    
	insert factura(id_cliente,fecha,id_vendedor,id_equipo,tipoVenta) 
		values(
			@idCliente,
            now(),
            @idVendedor,
            @idEquipo,
            tipoVenta);
END $$

delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `set_garantia`(mesesGarantia int)
BEGIN
	insert into garantia(meses_garantia) values(mesesGarantia);
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `set_marca`(marca varchar(45))
BEGIN
	insert into marca(nombre) values(marca);
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `set_proveedor`(nombre varchar(45))
BEGIN
	insert into proveedor(nombre) values(nombre);
END $$


delimiter $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `set_vendedor`(nombre varchar(45),apellido varchar(45),cedula varchar(14))
BEGIN
	insert into vendedor(nombre,apellido,cedula) values(nombre,apellido,cedula);
END $$

--  set equipos 

call set_equipo("Monitor",5000,"Distribuidora Corripio","Toyota","12","resolucion: 720p; color: rojo;");
call set_equipo("Luces quirurgicas",3500,"Distribuidora Corripio","Hyundai","12","color: blanca; voltaje: 24v");
call set_equipo("Mesa Medica",45000,"Distribuidora Corripio","Fun-chan-gan","24","color: azul; dimensiones: 100 x 200 x 50 cm");




--  set facturas 


call set_factura("40200000002","Julio Alcantara","Hyundai Luces quirurgicas","credito");
call set_factura("40200000003","Manuela Lopez","Fun-chan-gan Mesa Medica","contado");
call set_factura("40200000003","Manuela Lopez","Toyota Monitor","credito");


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;